services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-value} 
  front:
    build:
      context: ../aventureo-front
      dockerfile: ../aventureo-front/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api